import { readFile, writeFile, mkdir, copyFile } from "node:fs/promises";
import sharp from "sharp";
import { fileURLToPath } from "node:url";

// Bundled artwork only. Runtime pages never fetch assets from a server.
const assets = new URL("./extension/assets/", import.meta.url);
await mkdir(assets, { recursive: true });
const master = await readFile(
  new URL("../brand/keydrop-mark.svg", import.meta.url),
);
await writeFile(new URL("mark.svg", assets), master);
await sharp(master)
  .resize(1024, 1024)
  .png()
  .toFile(fileURLToPath(new URL("../brand/keydrop-mark.png", import.meta.url)));
await sharp(master)
  .resize(256, 256)
  .png()
  .toFile(fileURLToPath(new URL("mark.png", assets)));
for (const size of [16, 32, 48, 128]) {
  await sharp(master)
    .resize(size, size)
    .flatten({ background: "#ffffff" })
    .png()
    .toFile(fileURLToPath(new URL(`icon-${size}.png`, assets)));
}
const icons = {};
for (const name of [
  "eye",
  "eye-off",
  "plus",
  "minus",
  "clipboard",
  "file",
  "arrow-up-right",
  "check",
  "alert-circle",
  "loader",
  "chevron-down",
  "trash",
  "shield-lock",
]) {
  icons[name] = (
    await readFile(
      new URL(
        `./node_modules/@tabler/icons/icons/outline/${name}.svg`,
        import.meta.url,
      ),
      "utf8",
    )
  ).replace("<svg ", '<svg aria-hidden="true" focusable="false" ');
}
// Raw pixels avoid image URLs in the page badge, including on sites with img-src 'none'.
const logo = await sharp(master).resize(64, 64).ensureAlpha().raw().toBuffer();
await writeFile(
  new URL("./extension/assets.js", import.meta.url),
  `// Generated by build-assets.mjs from local artwork and Tabler Icons (MIT).\n// Static artwork only; never put user data in this file.\nglobalThis.KeyDropAssets = Object.freeze(${JSON.stringify({ logoPixels: logo.toString("base64"), logoSize: 64, icons })});\n`,
);
await copyFile(
  new URL("../brand/LOBE-ICONS-LICENSE.txt", import.meta.url),
  new URL("LOBE-ICONS-LICENSE.txt", assets),
);
await copyFile(
  new URL("./node_modules/@tabler/icons/LICENSE", import.meta.url),
  new URL("TABLER-LICENSE.txt", assets),
);
console.log("Built local KeyDrop artwork and icons.");
